# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20180530_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='present_students',
        ),
        migrations.AddField(
            model_name='attendance',
            name='present_students',
            field=models.ManyToManyField(blank=True, to='server.Student'),
        ),
    ]
