# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20180530_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='location',
        ),
        migrations.AddField(
            model_name='attendance',
            name='position',
            field=geoposition.fields.GeopositionField(default='', max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
