# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20180530_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='present_students',
            field=models.ManyToManyField(blank=True, to='server.Student'),
        ),
    ]
