# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20180616_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
